### ITCS-5111 Intro to Natural Language Processing

<a href="#Question 1 Answer" style="color:blue;">Click here to have a look at Answer to Question-1 Assigning Class Labels for the combined Dataframe</a>

<a href="#Question 2 Split the Dataset" style="color:blue;">Click here to have a look at Answer to Question-2 Split the Dataset</a>

<a href="#Question 3 Answer Majority Class Baseline" style="color:blue;">Click here to have a look at Answer to Question-3 Majority Class Baseline</a>

<a href="#Question 4 Target Length Baseline" style="color:blue;">Click here to have a look at Answer to Question-4 Target Length Baseline</a>

<a href="#Question 5 Answer_predict_HIGH_LOW" style="color:blue;">Click here to have a look at Answer to Question-5 - Predict whether the text is HIGH concrete or LOW concrete</a>

<a href="#Question 6 Answer_Result_Comparison" style="color:blue;">Click here to have a look at Answer to Question-6 - Model Result Comparison</a>

<a href="#Question 7 Answer_Different_Thresholds" style="color:blue;">Click here to have a look at Answer to Question 7 - Different Thresholds</a>

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import nltk
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [2]:
# Load the course data files for English into a dataframe using Pandas
dataframe_english = pd.read_csv(r"C:\Users\muthu\Desktop\UNCC\Semester-3\NLP\Assignments\Data_Input\CONcreTEXT_trial_EN.tsv", sep = "\t")
dataframe_english

TARGET POS  INDEX                                               TEXT  \
0   achievement   N      3  Bring up academic achievements , awards , and ...   
1   achievement   N      9  Please list people you have helped , your pers...   
2      activate   V      1     Add activated carbon straight to your vodka .    
3      activate   V     15  Place sensors around your garden , and when a ...   
4     adventure   N      9  Look for a partner that shares your level of a...   
..          ...  ..    ...                                                ...   
95        water   N      5  Rinse your face with warm water and pat it dry .    
96          win   V      4  Staying mentally strong means winning half the...   
97          win   V      7  The person who has the highest score wins the ...   
98        woman   N      7  For the most part , men and women wear the sam...   
99        woman   N      3  Look at the woman whom you are listening to fo...   

    MEAN  
0   3.06  
1   3.03  
2   3.83  
3   5.51  
4   2.03  
..   ...  
95  6.91  
96  2.34  
97  4.60  
98  6.29  
99  6.57  

[100 rows x 5 columns]

In [3]:
# Load the course data files for Italian into a dataframe using Pandas
dataframe_italian = pd.read_csv(r"C:\Users\muthu\Desktop\UNCC\Semester-3\NLP\Assignments\Data_Input\CONcreTEXT_trial_IT.tsv", sep = "\t")
dataframe_italian

TARGET POS  INDEX                                               TEXT  \
0   affascinare   V      8  Guardati i piedi o fai finta di essere affasci...   
1   affascinare   V      1  Sei affascinato dal funzionamento della mente ...   
2         amore   N      5  Pensa ai tuoi sentimenti di amore , passione e...   
3         amore   N      7  Quasi tutti sono in grado di ricevere amore e ...   
4          aria   N      4  Accendi il condizionatore sull’ aria fredda ma...   
..          ...  ..    ...                                                ...   
95       verità   N      8  In un modo o nell' altro , la verità viene sem...   
96      viaggio   N      2  Organizza dei viaggi nel fine settimana quando...   
97      viaggio   N      6  Pesa le tue valigie prima del viaggio per evit...   
98        vista   N      6  è molto importante non perdere di vista la pro...   
99        vista   N      9  i conigli hanno un ottimo udito e un' ottima v...   

    MEAN  
0   2.39  
1   2.03  
2   2.71  
3   2.16  
4   5.68  
..   ...  
95  2.53  
96  5.03  
97  4.84  
98  2.22  
99  5.13  

[100 rows x 5 columns]

In [4]:
# Combining both the dataframes using concat function in pandas
combined_dataframe = pd.concat([dataframe_english, dataframe_italian])
combined_dataframe

TARGET POS  INDEX                                               TEXT  \
0   achievement   N      3  Bring up academic achievements , awards , and ...   
1   achievement   N      9  Please list people you have helped , your pers...   
2      activate   V      1     Add activated carbon straight to your vodka .    
3      activate   V     15  Place sensors around your garden , and when a ...   
4     adventure   N      9  Look for a partner that shares your level of a...   
..          ...  ..    ...                                                ...   
95       verità   N      8  In un modo o nell' altro , la verità viene sem...   
96      viaggio   N      2  Organizza dei viaggi nel fine settimana quando...   
97      viaggio   N      6  Pesa le tue valigie prima del viaggio per evit...   
98        vista   N      6  è molto importante non perdere di vista la pro...   
99        vista   N      9  i conigli hanno un ottimo udito e un' ottima v...   

    MEAN  
0   3.06  
1   3.03  
2   3.83  
3   5.51  
4   2.03  
..   ...  
95  2.53  
96  5.03  
97  4.84  
98  2.22  
99  5.13  

[200 rows x 5 columns]

<a id="Question 1 Answer">
</a>

## Question-1 Answer - Assigning Class Labels for the combined Dataframe

In [5]:
# Question-1
condition = [combined_dataframe['MEAN'] <= 4, combined_dataframe['MEAN'] > 4]
class_labels = ["LOW", 'HIGH']
    
combined_dataframe['CONCRETE'] = np.select(condition, class_labels)
combined_dataframe

TARGET POS  INDEX                                               TEXT  \
0   achievement   N      3  Bring up academic achievements , awards , and ...   
1   achievement   N      9  Please list people you have helped , your pers...   
2      activate   V      1     Add activated carbon straight to your vodka .    
3      activate   V     15  Place sensors around your garden , and when a ...   
4     adventure   N      9  Look for a partner that shares your level of a...   
..          ...  ..    ...                                                ...   
95       verità   N      8  In un modo o nell' altro , la verità viene sem...   
96      viaggio   N      2  Organizza dei viaggi nel fine settimana quando...   
97      viaggio   N      6  Pesa le tue valigie prima del viaggio per evit...   
98        vista   N      6  è molto importante non perdere di vista la pro...   
99        vista   N      9  i conigli hanno un ottimo udito e un' ottima v...   

    MEAN CONCRETE  
0   3.06      LOW  
1   3.03      LOW  
2   3.83      LOW  
3   5.51     HIGH  
4   2.03      LOW  
..   ...      ...  
95  2.53      LOW  
96  5.03     HIGH  
97  4.84     HIGH  
98  2.22      LOW  
99  5.13     HIGH  

[200 rows x 6 columns]

<a id="Question 2 Split the Dataset">
</a>

## Question-2 Answer - Split the Dataset

In [6]:
combined_dataframe['LEN_OF_CHAR_TARGET'] = combined_dataframe['TARGET'].str.len()
combined_dataframe

TARGET POS  INDEX                                               TEXT  \
0   achievement   N      3  Bring up academic achievements , awards , and ...   
1   achievement   N      9  Please list people you have helped , your pers...   
2      activate   V      1     Add activated carbon straight to your vodka .    
3      activate   V     15  Place sensors around your garden , and when a ...   
4     adventure   N      9  Look for a partner that shares your level of a...   
..          ...  ..    ...                                                ...   
95       verità   N      8  In un modo o nell' altro , la verità viene sem...   
96      viaggio   N      2  Organizza dei viaggi nel fine settimana quando...   
97      viaggio   N      6  Pesa le tue valigie prima del viaggio per evit...   
98        vista   N      6  è molto importante non perdere di vista la pro...   
99        vista   N      9  i conigli hanno un ottimo udito e un' ottima v...   

    MEAN CONCRETE  LEN_OF_CHAR_TARGET  
0   3.06      LOW                  11  
1   3.03      LOW                  11  
2   3.83      LOW                   8  
3   5.51     HIGH                   8  
4   2.03      LOW                   9  
..   ...      ...                 ...  
95  2.53      LOW                   6  
96  5.03     HIGH                   7  
97  4.84     HIGH                   7  
98  2.22      LOW                   5  
99  5.13     HIGH                   5  

[200 rows x 7 columns]

In [7]:
combined_dataframe['TARGET_str_len_concrete'] = np.where(combined_dataframe['TARGET'].str.len() >= 5, 'HIGH', 'LOW')
combined_dataframe

TARGET POS  INDEX                                               TEXT  \
0   achievement   N      3  Bring up academic achievements , awards , and ...   
1   achievement   N      9  Please list people you have helped , your pers...   
2      activate   V      1     Add activated carbon straight to your vodka .    
3      activate   V     15  Place sensors around your garden , and when a ...   
4     adventure   N      9  Look for a partner that shares your level of a...   
..          ...  ..    ...                                                ...   
95       verità   N      8  In un modo o nell' altro , la verità viene sem...   
96      viaggio   N      2  Organizza dei viaggi nel fine settimana quando...   
97      viaggio   N      6  Pesa le tue valigie prima del viaggio per evit...   
98        vista   N      6  è molto importante non perdere di vista la pro...   
99        vista   N      9  i conigli hanno un ottimo udito e un' ottima v...   

    MEAN CONCRETE  LEN_OF_CHAR_TARGET TARGET_str_len_concrete  
0   3.06      LOW                  11                    HIGH  
1   3.03      LOW                  11                    HIGH  
2   3.83      LOW                   8                    HIGH  
3   5.51     HIGH                   8                    HIGH  
4   2.03      LOW                   9                    HIGH  
..   ...      ...                 ...                     ...  
95  2.53      LOW                   6                    HIGH  
96  5.03     HIGH                   7                    HIGH  
97  4.84     HIGH                   7                    HIGH  
98  2.22      LOW                   5                    HIGH  
99  5.13     HIGH                   5                    HIGH  

[200 rows x 8 columns]

In [8]:
# Spliting the training and test data set in 80% : 20% using train_test_split

combined_df_train, combined_df_test = train_test_split(combined_dataframe, test_size=0.2, shuffle=True, random_state=42)

print("\t English Language Train data: \n\n", combined_df_train.head(5), "\n\n Length of the Train data is: ", len(combined_df_train))
print('\n')
print("***********************************************************")
print('\n')
print("\t English Language Test data: \n\n", combined_df_test.head(5), "\n\n Length of the Train data is: ", len(combined_df_test))

	 English Language Train data: 

       TARGET POS  INDEX                                               TEXT  \
79   pollute   V      4  Producing too much trash pollutes the environm...   
97   viaggio   N      6  Pesa le tue valigie prima del viaggio per evit...   
38     field   N     14  As your nerves become increasingly more damage...   
24  decorate   V      5  Complete your grocery shopping , decorate the ...   
22     corpo   N      1  Il corpo umano è abitudinario e rispetta dei r...   

    MEAN CONCRETE  LEN_OF_CHAR_TARGET TARGET_str_len_concrete  
79  5.14     HIGH                   7                    HIGH  
97  4.84     HIGH                   7                    HIGH  
38  3.55      LOW                   5                    HIGH  
24  5.14     HIGH                   8                    HIGH  
22  6.23     HIGH                   5                    HIGH   

 Length of the Train data is:  160


***********************************************************


	 English La

## Majority Class Baseline

In [9]:
from sklearn.dummy import DummyClassifier
X = combined_df_train['TEXT']
y = combined_df_train['CONCRETE']
dummy_clf = DummyClassifier(strategy="most_frequent")

In [10]:
dummy_clf.fit(X, y)

DummyClassifier(constant=None, random_state=None, strategy='most_frequent')

In [11]:
predict_value = dummy_clf.predict(combined_df_test['CONCRETE'])
predict_value

array(['HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH',
       'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH',
       'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH',
       'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH',
       'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH', 'HIGH'],
      dtype='<U4')

In [12]:
target_names = combined_df_train['CONCRETE'].unique()
target_names

array(['HIGH', 'LOW'], dtype=object)

<a id="Question 3 Answer Majority Class Baseline">
</a>

## Question-3 Answer - Majority Class Baseline

In [13]:
print(metrics.classification_report(combined_df_test['CONCRETE'], predict_value,
    target_names=target_names))

metrics.confusion_matrix(combined_df_test['CONCRETE'], predict_value)

              precision    recall  f1-score   support

        HIGH       0.72      1.00      0.84        29
         LOW       0.00      0.00      0.00        11

    accuracy                           0.73        40
   macro avg       0.36      0.50      0.42        40
weighted avg       0.53      0.72      0.61        40



C:\Users\muthu\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[29,  0],
       [11,  0]], dtype=int64)

## Target Length Baseline

<a id="Question 4 Target Length Baseline">
</a>


## Question-4 Answer - Target Length Baseline

In [14]:
y_pred = combined_df_test['TARGET_str_len_concrete']

In [15]:
target_names = combined_dataframe['CONCRETE'].unique()

print(metrics.classification_report(combined_df_test['CONCRETE'], y_pred,
    target_names=target_names))

metrics.confusion_matrix(combined_df_test['CONCRETE'], y_pred)

              precision    recall  f1-score   support

         LOW       0.71      0.76      0.73        29
        HIGH       0.22      0.18      0.20        11

    accuracy                           0.60        40
   macro avg       0.47      0.47      0.47        40
weighted avg       0.58      0.60      0.59        40



array([[22,  7],
       [ 9,  2]], dtype=int64)

## Predict whether the text is HIGH concrete or LOW concrete

In [16]:
# CountVectorizer() is used for Text preprocessing, tokenizing and filtering of stopwords in the given text.
count_vect = CountVectorizer()
combined_train_data_count_vect = count_vect.fit_transform(combined_df_train['TEXT'])
combined_train_data_count_vect.shape

(160, 1117)

In [17]:
combined_df_train['TEXT']

79    Producing too much trash pollutes the environm...
97    Pesa le tue valigie prima del viaggio per evit...
38    As your nerves become increasingly more damage...
24    Complete your grocery shopping , decorate the ...
22    Il corpo umano è abitudinario e rispetta dei r...
                            ...                        
6     Osserva come lo zentangle si differenzia dalle...
14    Expenses include : rent , monthly loans , car ...
92    Talk about the places you 've traveled , the c...
79         Sorridi mentre parli o mentre vi salutate . 
2     Pensa ai tuoi sentimenti di amore , passione e...
Name: TEXT, Length: 160, dtype: object

In [18]:
# TfidfTransformer() is used for converting the words occurrences to frequencies
tfidf_transformer = TfidfTransformer()
combined_train_data_count_vect_tfidf = tfidf_transformer.fit_transform(combined_train_data_count_vect)
combined_train_data_count_vect_tfidf.shape

(160, 1117)

In [19]:
naive_bayes_model = MultinomialNB().fit(combined_train_data_count_vect_tfidf, combined_df_train['CONCRETE'])
naive_bayes_model

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

<a id="Question 5 Answer_predict_HIGH_LOW">
</a>

## Question-5 Answer - Predict whether the text is HIGH concrete or LOW concrete

In [20]:
category = ['HIGH', 'LOW']
docs_new = combined_df_test['TEXT']
X_new_counts = count_vect.transform(docs_new)
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

predicted = naive_bayes_model.predict(X_new_tfidf)
predicted

for doc, category in zip(docs_new, predicted):
    #print(predicted)
    print('%r => %s' % (doc, category))

'Rinse your face with warm water and pat it dry . ' => HIGH
'When you leave the seat of your car , you take some of this charge with you . ' => HIGH
'Consider opening the oven door slightly and allowing the pan to cool for a few minutes . ' => HIGH
'Non mettere tuo figlio in punizione perché si masturba . ' => HIGH
'Generalmente , i dipendenti detestano i meeting eccessivamente lunghi , e a ragione . ' => HIGH
'Tenere una volpe in casa è illegale in molti Paesi . ' => HIGH
'Watch a funny movie or television show . ' => HIGH
'Non puoi fare due bracciate prendendo il respiro solo una volta , pena la squalifica . ' => HIGH
"Connetti l' altro capo del cavo alla porta di ingresso del preamplificatore . " => HIGH
'Upon grabbing the deck , turn your entire hand over , causing the cards to be face down . ' => HIGH
'Dress in a professional manner for your interview . ' => HIGH
'In questo modo non dovrai creare spazio sul tuo cellulare per il file di aggiornamento . ' => LOW
'La maschera al miel

In [21]:
category = ['HIGH', 'LOW']
print(metrics.classification_report(combined_df_test['CONCRETE'], predicted,
    target_names=category))

metrics.confusion_matrix(combined_df_test['CONCRETE'], predicted)

              precision    recall  f1-score   support

        HIGH       0.74      0.97      0.84        29
         LOW       0.50      0.09      0.15        11

    accuracy                           0.73        40
   macro avg       0.62      0.53      0.49        40
weighted avg       0.67      0.72      0.65        40



array([[28,  1],
       [10,  1]], dtype=int64)

<a id="Question 6 Answer_Result_Comparison">
</a>

## Question-6 Answer - Model Result Comparison

From the above result we can see that the accuracy wise Majority Class baseline model and Naive Bayes Classifier produces the same accuracy of 73% whereas Target length baseline model gives 60% accuracy. Although Majority Class baseline model and Naive Bayes Classifier gives same accuracy result, its precision & recall value differs as (0.72, 1) and (0.74, 0.97) respectively. Also, majority class baseline model considers only the most frequent class not all the classes. But NB includes all the classes and gives an accuracy of 73% which is better than majority class baseline. 

As a result of comparing all the 3 models, based on the above outcome, NB classifier performed better.

<a id="Question 7 Answer_Different_Thresholds">
</a>

## Question-7 Answer - Different Thresholds


In [22]:
df = combined_dataframe 
df

TARGET POS  INDEX                                               TEXT  \
0   achievement   N      3  Bring up academic achievements , awards , and ...   
1   achievement   N      9  Please list people you have helped , your pers...   
2      activate   V      1     Add activated carbon straight to your vodka .    
3      activate   V     15  Place sensors around your garden , and when a ...   
4     adventure   N      9  Look for a partner that shares your level of a...   
..          ...  ..    ...                                                ...   
95       verità   N      8  In un modo o nell' altro , la verità viene sem...   
96      viaggio   N      2  Organizza dei viaggi nel fine settimana quando...   
97      viaggio   N      6  Pesa le tue valigie prima del viaggio per evit...   
98        vista   N      6  è molto importante non perdere di vista la pro...   
99        vista   N      9  i conigli hanno un ottimo udito e un' ottima v...   

    MEAN CONCRETE  LEN_OF_CHAR_TARGET TARGET_str_len_concrete  
0   3.06      LOW                  11                    HIGH  
1   3.03      LOW                  11                    HIGH  
2   3.83      LOW                   8                    HIGH  
3   5.51     HIGH                   8                    HIGH  
4   2.03      LOW                   9                    HIGH  
..   ...      ...                 ...                     ...  
95  2.53      LOW                   6                    HIGH  
96  5.03     HIGH                   7                    HIGH  
97  4.84     HIGH                   7                    HIGH  
98  2.22      LOW                   5                    HIGH  
99  5.13     HIGH                   5                    HIGH  

[200 rows x 8 columns]

In [23]:
def threshold_function (n):
    df['TARGET_str_len_concrete'] = np.where(df['LEN_OF_CHAR_TARGET'] >= n, 'HIGH', 'LOW')
    train, test = train_test_split(df, test_size=0.2, random_state=42, shuffle=True)
    target_names = test['CONCRETE'].unique()
    print(metrics.classification_report(test['CONCRETE'], test['TARGET_str_len_concrete'],
    target_names=target_names))
    print(metrics.confusion_matrix(test['CONCRETE'], y_pred))

In [24]:
threshold_function(7)

              precision    recall  f1-score   support

        HIGH       0.67      0.34      0.45        29
         LOW       0.24      0.55      0.33        11

    accuracy                           0.40        40
   macro avg       0.45      0.45      0.39        40
weighted avg       0.55      0.40      0.42        40

[[22  7]
 [ 9  2]]


In [25]:
threshold_function(3)

              precision    recall  f1-score   support

        HIGH       0.72      1.00      0.84        29
         LOW       0.00      0.00      0.00        11

    accuracy                           0.73        40
   macro avg       0.36      0.50      0.42        40
weighted avg       0.53      0.72      0.61        40

[[22  7]
 [ 9  2]]


C:\Users\muthu\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
threshold_function(2)

              precision    recall  f1-score   support

        HIGH       0.72      1.00      0.84        29
         LOW       0.00      0.00      0.00        11

    accuracy                           0.73        40
   macro avg       0.36      0.50      0.42        40
weighted avg       0.53      0.72      0.61        40

[[22  7]
 [ 9  2]]


I have chosen three different threshold values for the Target length 7, 3 and 2 respectively. I chose >=7 as HIGH because, in Q4 we have set the threshold as >=5 and the model gave accuracy as 60%, so I felt that increasing the threshold value would increase the accuracy of the model. But to my suprise, the model performed vice versa. It gave me an accuracy of 40%. 

So, for my next option I chose 2 value less than Q4 (>=5) since the first threshold is two value higher than Q4 threshold, i.e., I opted for 3 as my threshold. The model performed really well and gave me an output of 73% when compared to threshold values >=5 and >=7.

Next, I still wanted to improve the accuracy of the model and reduced my threshold value to >= 2. But the model gave me the same output as of threshold value >= 3. Hence, I finalized that the Target length baseline model gave its best accuracy of 73% at threshold value >=3 and >=2 which equals the NB and majority class baseline accuracy.